In [1]:
# converting iD into 2D
# .reshape() is the methord which is used for reshape the arrays.

import numpy as np

#create a 1D array
array_1D = np.array([1,2,3,4,5,6])
print("array1D :", array_1D)
print("shape of  array1D :", array_1D.shape)

array1D : [1 2 3 4 5 6]
shape of  array1D : (6,)


In [2]:
#reshape the 1D array to array
array_2D = array_1D.reshape(2,3)
print ("2D array :", array_2D)
print("shape of array_2D :", array_2D.shape)

2D array : [[1 2 3]
 [4 5 6]]
shape of array_2D : (2, 3)


In [3]:
#reshape 1D array in to 3D array
array_3D = array_1D.reshape(2,3,1)
print("3D array :", array_3D)
print ("shape of array_3D :", array_3D.shape)

3D array : [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
shape of array_3D : (2, 3, 1)


In [5]:
import numpy as np

array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2D)

for elements in np.nditer(array_2D):
    print(elements)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9
